<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jstp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^.*\bfunction\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JavaScript Text Preprocessing</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;%=?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.jstp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(%&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;@)(?!%&gt;)</string>
					<key>end</key>
					<string>(?=%&gt;)</string>
					<key>name</key>
					<string>source.jstp.embedded.c++</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c++</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jstp</string>
	<key>uuid</key>
	<string>0583c7b5-ca5c-4560-80d7-3d92e1d15f2b</string>
</dict>
</plist>
